"""
Django settings for 零食商城 project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mpvpxd(!9md4#vz&8k*74e6*d-d2#ieqt47zc&-h3%1c1s#i^h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']   # 开发环境先放开（上线前收紧）


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # CORS 就是浏览器的“跨域通行证”，专门防止前端乱调后端接口的“保安”。
    'corsheaders',       # Django 配置 CORS
    'product',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',        #必须放在最顶
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '零食商城.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '零食商城.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'product',
        'USER':'root',
        'PASSWORD':'123456',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

'''
JWT 配置步骤（本次项目实操记录）:
1. 安装包:
   pip install djangorestframework-simplejwt

2. settings.py 配置（文件末尾加）:
   REST_FRAMEWORK = {
       'DEFAULT_AUTHENTICATION_CLASSES': [
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ],
   }
   SIMPLE_JWT = {
       'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # access 30分钟过期
       'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # refresh 7天过期
   }

3. urls.py 注册两个自带视图（不用自己写登录逻辑）:
   from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
   path('login/', TokenObtainPairView.as_view()),    # POST 用户名密码 → 返回 token
   path('refresh/', TokenRefreshView.as_view()),     # POST refresh token → 换新 access

4. 测试:
   POST /api/login/  body={"username":"张三","password":"123456"}
   → 返回 {"access": "...", "refresh": "..."}

5. 带 token 访问:
   Header:  Authorization: Bearer <access值>

踩坑记录:
   - import simplejwt 前必须先 django.setup()（直接 python 运行要设 DJANGO_SETTINGS_MODULE）
   - 项目目录运行才找得到 '零食商城.settings'
   - access 和 refresh 是两个不同的 token，别搞混
'''

# ============ JWT 配置 ============
# 告诉 DRF："接口验证身份时用 JWT"
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':timedelta(minutes=30),  # 身份证 30 分钟过期
    'REFRESH_TOKEN_LIFETIME':timedelta(days=7),      # 到期后可以"续签"，7 天内都行
}

'''
CORS流程
步骤	        代码位置	        一句话
① 装包	    pip	            django-cors-headers
② 注册	    INSTALLED_APPS  加 'corsheaders'
③ 中间件	    MIDDLEWARE	    CorsMiddleware  放最顶
④ 允许来源	文件末尾	        CORS_ALLOW_ALL_ORIGINS = True（开发）
'''

# ============ CORS 跨域配置 ============
CORS_ALLOW_ALL_ORIGINS = True   # 开发环境：允许所有来源（上线前要改）
CORS_ALLOW_CREDENTIALS = True   # 允许携带 token（Cookie/Authorization 头）

# 关掉自动补斜杠（避免前端无斜杠请求被 301 重定向导致 bug）
APPEND_SLASH = False

# ============ Redis 缓存配置 ============
# 告诉 Django："所有缓存统一用 Redis，别用默认的内存缓存"
CACHES = {
    'default' : {
        'BACKEND' : 'django_redis.cache.RedisCache',    # 用 django-redis 这个后端
        'LOCATION' : 'redis://127.0.0.1:6379/1',        # Redis 地址：本机 + 6379端口 + 1号库
        'OPTIONS' : {
            'CLIENT_CLASS' : 'django_redis.client.DefaultClient',
        }
    }
}